// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuU0Q6raEsXr5HcDF7jJX-mmKRbU7z7x8',
    appId: '1:779452748415:web:6d3a743e1bdf416d75254a',
    messagingSenderId: '779452748415',
    projectId: 'al-mathina-f75c0',
    authDomain: 'al-mathina-f75c0.firebaseapp.com',
    storageBucket: 'al-mathina-f75c0.firebasestorage.app',
    measurementId: 'G-NNKLET6MZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0w44-Er2OzpXNQ0hkjP1I4rFOLmcBRB0',
    appId: '1:779452748415:android:6f52b3e15f01453775254a',
    messagingSenderId: '779452748415',
    projectId: 'al-mathina-f75c0',
    storageBucket: 'al-mathina-f75c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuPAl_f5uy5uqS5aCuEMDHiv0Vsa7GIA',
    appId: '1:779452748415:ios:d06450060ce90fec75254a',
    messagingSenderId: '779452748415',
    projectId: 'al-mathina-f75c0',
    storageBucket: 'al-mathina-f75c0.firebasestorage.app',
    iosBundleId: 'com.example.flutterPreview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATuPAl_f5uy5uqS5aCuEMDHiv0Vsa7GIA',
    appId: '1:779452748415:ios:d06450060ce90fec75254a',
    messagingSenderId: '779452748415',
    projectId: 'al-mathina-f75c0',
    storageBucket: 'al-mathina-f75c0.firebasestorage.app',
    iosBundleId: 'com.example.flutterPreview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuU0Q6raEsXr5HcDF7jJX-mmKRbU7z7x8',
    appId: '1:779452748415:web:d69543397e2e758375254a',
    messagingSenderId: '779452748415',
    projectId: 'al-mathina-f75c0',
    authDomain: 'al-mathina-f75c0.firebaseapp.com',
    storageBucket: 'al-mathina-f75c0.firebasestorage.app',
    measurementId: 'G-WLBDJ9KTQW',
  );
}
