// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart' show dotenv;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWr3c373kCJ9bneDJasqLpNAK1Og0UhuU',
    appId: '1:753225358557:android:5aa8dd7a891f803058cf34',
    messagingSenderId: '753225358557',
    projectId: 'al-mathina',
    storageBucket: 'al-mathina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWr3c373kCJ9bneDJasqLpNAK1Og0UhuU',
    appId: '1:753225358557:ios:replace-with-ios-app-id',
    messagingSenderId: '753225358557',
    projectId: 'al-mathina',
    storageBucket: 'al-mathina.firebasestorage.app',
    iosBundleId: 'com.vectorai.almadhina',
  );
}

import 'dart:io';

TargetPlatform get defaultTargetPlatform {
  if (Platform.isAndroid) {
    return TargetPlatform.android;
  }
  if (Platform.isIOS) {
    return TargetPlatform.iOS;
  }
  throw UnsupportedError('Unsupported platform');
}
